### PR TITLE
Add monad interfaces instances for Hydra and fix Hydra.Interface

### LINKED ISSUE #125: Add support for Hydra in off-chain util functions
Probably we need to add Runner param for hydra-node. I think in end we need to have most of tx submitting functions work on both L1 or L2 dependent on this param.

* Support submitting custom Tx on hydra
* Support query UTxOs from Hydra-node
     * Decide on snapshots and ouptut parsing
     * Add some kind of polymorphism to query functions I guess
* Add L2 version of E2E Ledger test

### PR DESCRIPTION
**Pull request by uhbif19**
Closes #125 

Blocked by #225

### CODE REVIEW

File: src/HydraAuction/Hydra/Interface.hs [hunk 1]
```diff
@@ -1,3 +1,74 @@
...
+  | TxSeenKind
+  | CommittedKind
+  | HeadIsInitializingKind
+  | HeadIsOpenKind
+  | HeadIsClosedKind
+  | ReadyToFanoutKind
+  | HeadIsFinalizedKind
+  deriving stock (Eq)
+
+getHydraEventKind :: HydraEvent -> HydraEventKind
```
Comment (nazrhom) [inline src/HydraAuction/Hydra/Interface.hs:71]: I think we can use makePrisms for `HydraEvent` to achieve something similar. We can also remove the reification of `AwaitedHydraEvent` and make it `type AwaitedHydraEvent = HydraEvent -> Bool` so the generated functions can be used to check which constructor is chosen

Comment (uhbif19) [reply src/HydraAuction/Hydra/Interface.hs:71]: > I think we can use makePrisms for HydraEvent to achieve something similar.

Thanks, that seems like exactly the question I was talking about in haskell-learn channel.

I would not change that now, cuz I am bad at prisms, but you could refactor that later is you want to.

> make it type AwaitedHydraEvent = HydraEvent -> Bool so the generated functions can be used to check which constructor is chosen

Functions do not have Eq and are more obscure to understand. Also ADT AwaitedHydraEvent is able have some other implementation than filtering, in theory.

File: src/HydraAuction/Hydra/Interface.hs [hunk 2]
```diff
@@ -1,3 +1,74 @@
...
+data HydraCommand
+  = Init
+  | GetUTxO
+  | NewTx Tx
+  | Commit UTxO.UTxO
+  | Close
+  | Fanout
+  deriving stock (Show)
+
+commandConstructorName :: HydraCommand -> Text
```
Comment (MangoIV) [inline src/HydraAuction/Hydra/Interface.hs:34]: This can be done cleanly with Generics to avoid repetitions

File: src/HydraAuction/Hydra/Runner.hs [hunk 3]
```diff
@@ -0,0 +1,152 @@
...
+import HydraAuction.Hydra.Monad (
+  AwaitedHydraEvent (..),
+  MonadHydra (..),
+ )
+import HydraAuctionUtils.Monads (
+  MonadNetworkId (askNetworkId),
+  MonadTrace (..),
+ )
+
+{- HLINT ignore "Use newtype instead of data" -}
```
Comment (MangoIV) [inline src/HydraAuction/Hydra/Runner.hs:63]: This will trigger an unknown Pragma warning, do we have that warning enabled globally? I think it should be enabled per module.

File: src/HydraAuction/Hydra/Interface.hs (hunk 1 above)
Comment (MangoIV) [reply src/HydraAuction/Hydra/Interface.hs:71]: i think this can be done easier by having an NS that is tagged with a constructor name. This would be possible to be created generically. 

E.g. you could collect the constructor names of the type from its Rep in a list then have a GADT that witnesses that list.  The GADT could looks similar to NS from generics-sop

Comment (MangoIV) [reply src/HydraAuction/Hydra/Interface.hs:71]: Perhaps using lens is the better solution though.

File: src/HydraAuction/Hydra/Runner.hs (hunk 3 above)
Comment (uhbif19) [reply src/HydraAuction/Hydra/Runner.hs:63]: This is not a pragma, this is comment. For exactly that reason.

Comment (MangoIV) [reply src/HydraAuction/Hydra/Runner.hs:63]: OH, sorry then. the HLS action for this always adds a pragma and another pragma to ignore the hlint pragma, so that's why I'm used to seeing that.

File: src/HydraAuction/Hydra/Interface.hs (hunk 2 above)
Comment (uhbif19) [reply src/HydraAuction/Hydra/Interface.hs:34]: It could, but seems like quite overkill. Also we need ability to change encodings in case of Hydra API changes.

File: src/HydraAuction/Hydra/Monad.hs [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+
+waitForHydraEvent :: MonadHydra m => AwaitedHydraEvent -> m HydraEvent
+waitForHydraEvent = waitForHydraEvent' defaultTimeout
+
+sendCommandAndWaitFor :: MonadHydra m => AwaitedHydraEvent -> HydraCommand -> m HydraEvent
+sendCommandAndWaitFor awaitedSpec command = do
+  sendCommand command
+  waitForHydraEvent awaitedSpec
+
+instance (Monad m, MonadHydra m) => MonadSubmitTx m where
```
Comment (MangoIV) [inline src/HydraAuction/Hydra/Monad.hs]: `Monad m` should be subsumed by `MonadHydra`, but that's not so important

File: src/HydraAuction/Hydra/Monad.hs [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+  submitTx :: Tx -> m ()
+  submitTx = sendCommand . NewTx
+  awaitTx :: Tx -> m ()
+  awaitTx = void . waitForHydraEvent . SpecificEvent . TxSeen
+
+instance {-# OVERLAPPABLE #-} (Monad m, MonadHydra m) => MonadQueryUtxo m where
```
Comment (MangoIV) [inline src/HydraAuction/Hydra/Monad.hs:78]: This is probably not good practice, there's two possibilities to solve this in a better way: 
- use a `newtype` and `deriving via` 
- make a `default` declaration and use it with `deriving anyclass`

File: src/HydraAuction/Hydra/Runner.hs [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+  HydraRunner a ->
+  IO a
+executeHydraRunner context runner =
+  runReaderT (unHydraRunner runner) context
+
+executeHydraRunnerInTest :: HydraClient -> HydraRunner a -> IO a
+executeHydraRunnerInTest node = executeHydraRunner context
+  where
+    tracer = contramap show stdoutTracer
+    context = MkHydraExecutionContext {node = node, tracer = tracer}
```
Comment (MangoIV) [inline src/HydraAuction/Hydra/Runner.hs:174]:
```suggestion
    context = MkHydraExecutionContext node tracer
```

File: src/HydraAuction/Hydra/Runner.hs [hunk 7]
```diff
@@ -0,0 +1,152 @@
...
+instance MonadTrace HydraRunner where
+  type TracerMessage HydraRunner = HydraRunnerLog
+  stringToMessage = HydraRunnerStringMessage
+  traceMessage message = do
+    MkHydraExecutionContext {tracer} <- ask
+    liftIO $ traceWith tracer message
+
+matchingHydraEvent :: Value -> Maybe HydraEvent
+matchingHydraEvent value =
+  case value ^? key "tag" of
```
Comment (MangoIV) [inline src/HydraAuction/Hydra/Runner.hs:132]: I think with `Maybe` this will be kinda bad to debug, I think it would be nice to have a real Parser or some more informative error type instead

File: src/HydraAuction/Hydra/Monad.hs [hunk 8]
```diff
@@ -0,0 +1,72 @@
...
+    response <-
+      sendCommandAndWaitFor (SpecificKind GetUTxOResponseKind) GetUTxO
+    let utxo = case response of
+          GetUTxOResponse utxo' -> utxo'
+          _ -> error "Impossible happened: incorrect response type awaited"
+    return $ UTxO.fromPairs $ filter predicate $ UTxO.pairs utxo
+    where
+      predicate (txIn, TxOut (AddressInEra _ txOutAddress) _ _ _) = case query of
+        -- FIXUP: use safe coerce
+        ByAddress address -> txOutAddress == unsafeCoerce address
```
Comment (MangoIV) [inline src/HydraAuction/Hydra/Monad.hs]: why is this `unsafeCoerce`? I feel like this should at least be annotated with specific types such that it won't silently blow up.

Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs:71]: This cannot be safely coerced, ever.

Comment (MangoIV) [inline src/HydraAuction/Hydra/Monad.hs]:
```suggestion
        ByAddress address ->
          case txOutAddress of 
            addr@(ShelleyAddress _ _ _) -> 
              address == addr 
            ByronAddress _ -> error "didn't expect Byron address" 
```

File: src/HydraAuction/Hydra/Monad.hs [hunk 9]
```diff
@@ -0,0 +1,72 @@
...
+  sendCommandAndWaitFor,
+) where
+
+-- Prelude imports
+import Prelude
+
+-- Haskell imports
+import Control.Monad (void)
+import GHC.Natural (Natural)
+import Unsafe.Coerce (unsafeCoerce)
```
Comment (MangoIV) [inline src/HydraAuction/Hydra/Monad.hs]:
```suggestion
```

File: src/HydraAuction/Hydra/Monad.hs [hunk 10]
```diff
@@ -0,0 +1,72 @@
...
+
+-- Cardano imports
+import Cardano.Api (AddressInEra (..))
+import Cardano.Api.UTxO qualified as UTxO
+
+-- Hydra imports
+import Hydra.Cardano.Api (Tx)
```
Comment (MangoIV) [inline src/HydraAuction/Hydra/Monad.hs]:
```suggestion
import Hydra.Cardano.Api (Tx, Address (ByronAddress, ShelleyAddress))
```

File: src/HydraAuction/Hydra/Monad.hs (hunk 8 above)
Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs]: This can also be some real error with something like `filterM`

**Review by MangoIV — COMMENTED** [review]
Fix `unsafeCoerce`

File: src/HydraAuction/Hydra/Monad.hs (hunk 8 above)
Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs]: it's not as unsafe as I thought, because at least it's not a segfault, but I still think we should not do it. https://play.haskell.org/saved/UElf70yi

File: src/HydraAuction/Hydra/Runner.hs (hunk 7 above)
Comment (uhbif19) [reply src/HydraAuction/Hydra/Runner.hs:132]: This is not a parser and it does not have errors. This is matcher to await events.

File: src/HydraAuction/Hydra/Monad.hs (hunk 8 above)
Comment (uhbif19) [reply src/HydraAuction/Hydra/Monad.hs]: Thanks, will merge.

File: src/HydraAuction/Hydra/Monad.hs (hunk 4 above)
Comment (uhbif19) [reply src/HydraAuction/Hydra/Monad.hs]: This does not work, I do not know why.

> Could not deduce (Monad m)
>        arising from the superclasses of an instance declaration

Comment (uhbif19) [reply src/HydraAuction/Hydra/Monad.hs]: Lol, seems to be known issue, and examples are having the same Monad superclass too :D

https://gitlab.haskell.org/ghc/ghc/-/issues/14836

Comment (uhbif19) [reply src/HydraAuction/Hydra/Monad.hs]: Okay, I am wrong, UndecidableSuperClasses does not help. Which is quite understandable, cuz there is nothing recursive here.

I will just add FIXME.

File: src/HydraAuction/Hydra/Monad.hs (hunk 5 above)
Comment (uhbif19) [reply src/HydraAuction/Hydra/Monad.hs:78]: I do not see which problems could OVERLAPPABLE introduce. Especially given that we do all instances in same package. And MLabs styleguide does not mention overlapping.  And we already use bunch of Orphan instances.

It builds now without OVELAPPABLE now though. I am now sure why, probably we do not import both instances in same file.

File: src/HydraAuction/Hydra/Runner.hs (hunk 6 above)
Comment (uhbif19) [reply src/HydraAuction/Hydra/Runner.hs:174]: Named fields are better, cuz they provide explanation on arguments.

File: src/HydraAuction/Hydra/Monad.hs (hunk 8 above)
Comment (uhbif19) [reply src/HydraAuction/Hydra/Monad.hs]: Because I was lazy, will apply your patch, thanks.

File: src/HydraAuction/Hydra/Monad.hs (hunk 5 above)
Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs:78]: There's a couple of reasons why this is bad: 
- behavior may change by omitting an instance declaration 
- especially in combination with orphan instances this is incredibly dangerous
- I think it's generally best practice to not reach for OVERLAPPING and OVERLAPPABLE without good reasons, I don't see a good reason here because we could just have a `default` impl or a `newtype` wrapper, which are very nice solutions 
- also, that it works at the moment is because you don't use the instance. overlapping and overlappable errors are discovered at call sites.

Comment (uhbif19) [reply src/HydraAuction/Hydra/Monad.hs:78]: > also, that it works at the moment is because you don't use the instance

I think I checked this with instances.

File: src/HydraAuction/Hydra/Monad.hs (hunk 4 above)
Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs]:
```haskell

Main.hs:5:10: warning: [GHC-36038] [-Wloopy-superclass-solve]
    I am solving the constraint ‘Monad m’,
      arising from the superclasses of an instance declaration,
    in a way that might turn out to loop at runtime.
    Starting from GHC 9.10, this warning will turn into an error.
    See the user manual, § Undecidable instances and loopy superclasses.
    Suggested fix:
      Add the constraint ‘Monad m’ to the instance context,
      even though it seems logically implied by other constraints in the context.
```

Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs]: this is the reason.

Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs]: https://play.haskell.org/saved/WSLu5ueh

Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs]:
```mermaid
stateDiagram-v2
    Monad --> MonadA
    Monad --> MonadB 
```

Comment (uhbif19) [reply src/HydraAuction/Hydra/Monad.hs]: I forgot we have UndecidableInstances enabled globaly.

Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs]:
```mermaid
stateDiagram-v2
    Monad --> MonadA
    Monad --> MonadB 
    MonadA --> MonadB
```

Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs]: the above is the class relations and the below is the instance relation. Perhaps the reason is that it won't know whether to pick the instance that is implied by MonadB or the one that is implied by MonadA?

File: src/HydraAuction/Hydra/Monad.hs (hunk 5 above)
Comment (uhbif19) [reply src/HydraAuction/Hydra/Monad.hs:78]: Not sure how to deal with `newtype` for case of `* -> *` kinded types here. But you probably right that it is cleaner.

Please separate that to follow-up tech-debt issue.

File: src/HydraAuction/Hydra/Runner.hs (hunk 7 above)
Comment (MangoIV) [reply src/HydraAuction/Hydra/Runner.hs:132]: then this is really strange to me.

File: src/HydraAuction/Hydra/Monad.hs (hunk 5 above)
Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs:78]: `newtype Wrap f a = Wrap (f a)`

Comment (MangoIV) [reply src/HydraAuction/Hydra/Monad.hs:78]: however, you can also do a `default` decl

**Review by MangoIV — APPROVED** [review]

File: src/HydraAuction/Hydra/Runner.hs (hunk 7 above)
Comment (nazrhom) [reply src/HydraAuction/Hydra/Runner.hs:132]: I think this makes sense as a `Maybe`. We don't really know what to do with the error here. We want to run this over every event, to build a `HydraEvent` and then run a predicate on it. Using `Maybe` means we ignore every JSON value coming in that does not match what we expect.

File: src/HydraAuction/Hydra/Monad.hs [hunk 11]
```diff
@@ -0,0 +1,93 @@
...
+waitForHydraEvent :: MonadHydra m => AwaitedHydraEvent -> m HydraEvent
+waitForHydraEvent = waitForHydraEvent' defaultTimeout
+
+sendCommandAndWaitFor :: MonadHydra m => AwaitedHydraEvent -> HydraCommand -> m HydraEvent
+sendCommandAndWaitFor awaitedSpec command = do
+  sendCommand command
+  waitForHydraEvent awaitedSpec
+
+-- FIXME: this does not work without `Monad m`, do not know why
+instance {-# OVERLAPPABLE #-} (Monad m, MonadHydra m) => MonadSubmitTx m where
```
Comment (nazrhom) [inline src/HydraAuction/Hydra/Monad.hs:66]: I read the discussion in the other comment, I agree we can defer this to a follow-up PR. Maybe we could just add a comment here explaining why we are using overlappable

**Review by nazrhom — APPROVED** [review]
Looks good to me! Just added a note about explaining why we have the OVERLAPPABLE pragma

File: src/HydraAuction/Hydra/Monad.hs (hunk 11 above)
Comment (uhbif19) [reply src/HydraAuction/Hydra/Monad.hs:66]: Follow-up #237
